### ISSUE TITLE
Visual improvements to Finder

### ISSUE THREAD

**Issue by avalot** [openline-ai/openline-customer-os#1122]
Finder:
- [x] #1208

![image](https://user-images.githubusercontent.com/831133/222732604-669c2175-31e1-4668-b1a1-fc10a0078c9d.png)

- [x] #1206
- [x] #1207

![image](https://user-images.githubusercontent.com/831133/222733231-bad3aef3-ac25-453f-aae7-ccf589e41840.png)

- [x] [Consistent two-line layout on all records, matching the one on the header line. NO VERTICAL CENTERING.](https://github.com/openline-ai/openline-customer-os/issues/1226)

![image](https://user-images.githubusercontent.com/831133/222734418-2f514706-7f98-47a5-a223-dd5e15dbdb13.png)

- [x] [Remove "Default location" from the list. If there's no location name, keep that line blank.](https://github.com/openline-ai/openline-customer-os/issues/1225)

- [ ] Kebab menu: same distance from right as from top & bottom (68px width instead of 5%?)

![image](https://user-images.githubusercontent.com/831133/222735219-597f8d18-d1c9-48ef-9154-4558fc266f8f.png)

- [x] [The logo grows taller by 1 pixel when we expand the Meta panel. It should not rescale at all. (Recommend that you separate the logo mark from the word mark.)](https://github.com/openline-ai/openline-customer-os/issues/1224)

![image](https://user-images.githubusercontent.com/831133/222737054-20770c77-0841-472e-8aa6-57b9b1828b21.png)

**Comment by Kasia9090** [comment]
>  The logo grows taller by 1 pixel when we expand the Meta panel. It should not rescale at all. (Recommend that you separate the logo mark from the word mark.)

@avalot Those are two icons that are swapped when modal is open. I need either separate svg with only text or font used to create this text

**Comment by Kasia9090** [comment]
>  Remove "Default location" from the list. If there's no location name, keep that line blank.

Unlike 'unnamed' label for contact without name, 'default location' is not added on frontend, it comes from backend and should be filtered out there (FE should not know that there is specific location name that it needs to hide)

**Comment by Kasia9090** [comment]
>  Consistent two-line layout on all records, matching the one on the header line. NO VERTICAL CENTERING.

@avalot there are cases where whole row has just one line, without vertical centering it looks really bad and creates messy effect

**Comment by Kasia9090** [comment]
> Kebab menu: same distance from right as from top & bottom (68px width instead of 5%?)
 
 @avalot the menu button is in the same cell and "save" and "cancel" button. Changing width to suit measurements of icon button and then changing it to fit normal button will cause layout jump which we should avoid whenever possible.
 
I can propose instead using only icon buttons for those 3 actions (not sure if it will be best ux) or leaving wider cell to be prepared for showing save and edit buttons. 


In case you just want to move it closer to the right side (like shown on screenshot below) than let me know as this is possible and won't cause issues mentioned above (jump of content) and can be achieved by aligning button to the right.

If this is the desired effect please next time try to focus description on desired outcome from user perspective, not code solutions as paradoxically it makes it harder to understand what is desired outcome.

![Screenshot 2023-03-08 at 09 36 06](https://user-images.githubusercontent.com/121807793/223663740-007cd69e-352c-459b-a8d5-be8e390f8a4a.png)
